# Explore here

In [1]:
# Your code here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
main_df = pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/decision-tree-project-tutorial/main/diabetes.csv')

In [3]:
main_df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
X = main_df.drop(columns='Outcome')
y = main_df['Outcome']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [6]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [7]:
from sklearn.ensemble import GradientBoostingClassifier

In [8]:
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
397            0      131             66             40        0  34.3   
197            3      107             62             13       48  22.9   
294            0      161             50              0        0  21.9   
20             3      126             88             41      235  39.3   
767            1       93             70             31        0  30.4   
..           ...      ...            ...            ...      ...   ...   
457            5       86             68             28       71  30.2   
23             9      119             80             35        0  29.0   
686            3      130             64              0        0  23.1   
93             4      134             72              0        0  23.8   
257            2      114             68             22        0  28.7   

     DiabetesPedigreeFunction  Age  
397                     0.196   22  
197                     0.678   23  
294                     0.254   65  
20                      0.704   27  
767                     0.315   23  
..                        ...  ...  
457                     0.364   24  
23                      0.263   29  
686                     0.314   22  
93                      0.277   60  
257                     0.092   25  

[576 rows x 8 columns]

In [9]:
gra_boost_model = GradientBoostingClassifier(learning_rate=0.0001, n_estimators=100)

In [10]:
gra_boost_model.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.0001)

In [11]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [12]:
def scoring_make(model, X_train, X_test, y_train, y_test):
    y_train_preds = model.predict(X_train)
    y_test_preds = model.predict(X_test)

    print(f'accuracy of training dataset is {accuracy_score(y_true=y_train, y_pred=y_train_preds)}')
    print(f'accuracy of testing dataset is {accuracy_score(y_true=y_test, y_pred=y_test_preds)}')

    print('confusion matrix of training dataset is\n')
    print(confusion_matrix(y_true=y_train, y_pred=y_train_preds))
    print('confusion matrix of testing dataset is\n')
    print(confusion_matrix(y_true=y_test, y_pred=y_test_preds))

    print(f'classification report of training dataset is\n')
    print(classification_report(y_true=y_train, y_pred=y_train_preds))
    print(f'classification report of testing dataset is\n')
    print(classification_report(y_true=y_test, y_pred=y_test_preds))

In [13]:
scoring_make(gra_boost_model, X_train, X_test, y_train, y_test)

accuracy of training dataset is 0.6475694444444444
accuracy of testing dataset is 0.6614583333333334
confusion matrix of training dataset is

[[373   0]
 [203   0]]
confusion matrix of testing dataset is

[[127   0]
 [ 65   0]]
classification report of training dataset is

              precision    recall  f1-score   support

           0       0.65      1.00      0.79       373
           1       0.00      0.00      0.00       203

    accuracy                           0.65       576
   macro avg       0.32      0.50      0.39       576
weighted avg       0.42      0.65      0.51       576

classification report of testing dataset is

              precision    recall  f1-score   support

           0       0.66      1.00      0.80       127
           1       0.00      0.00      0.00        65

    accuracy                           0.66       192
   macro avg       0.33      0.50      0.40       192
weighted avg       0.44      0.66      0.53       192



/home/vscode/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/vscode/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/vscode/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/vscode/.local/li

In [14]:
from sklearn.model_selection import GridSearchCV

In [15]:
hyperparameters = {
    "learning_rate" : [0.1,0.2,0.3,0.4],
    "n_estimators" : [20, 50, 100, 150],
    "max_depth" : [2, 5, 8, 10],
    
}

In [16]:
grid_model = GridSearchCV(GradientBoostingClassifier(random_state=25), param_grid= hyperparameters, scoring="accuracy", cv = 5)

grid_model.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(random_state=25),
             param_grid={'learning_rate': [0.1, 0.2, 0.3, 0.4],
                         'max_depth': [2, 5, 8, 10],
                         'n_estimators': [20, 50, 100, 150]},
             scoring='accuracy')

In [17]:
grid_model.best_estimator_

GradientBoostingClassifier(learning_rate=0.3, max_depth=2, n_estimators=50,
                           random_state=25)

In [18]:
grid_model.best_params_

{'learning_rate': 0.3, 'max_depth': 2, 'n_estimators': 50}

In [19]:
best_gra_model = GradientBoostingClassifier(learning_rate = 0.1, max_depth = 2, n_estimators= 50)

In [20]:
best_gra_model.fit(X_train, y_train)

GradientBoostingClassifier(max_depth=2, n_estimators=50)

In [21]:
scoring_make(best_gra_model, X_train, X_test, y_train, y_test)

accuracy of training dataset is 0.8125
accuracy of testing dataset is 0.796875
confusion matrix of training dataset is

[[339  34]
 [ 74 129]]
confusion matrix of testing dataset is

[[113  14]
 [ 25  40]]
classification report of training dataset is

              precision    recall  f1-score   support

           0       0.82      0.91      0.86       373
           1       0.79      0.64      0.70       203

    accuracy                           0.81       576
   macro avg       0.81      0.77      0.78       576
weighted avg       0.81      0.81      0.81       576

classification report of testing dataset is

              precision    recall  f1-score   support

           0       0.82      0.89      0.85       127
           1       0.74      0.62      0.67        65

    accuracy                           0.80       192
   macro avg       0.78      0.75      0.76       192
weighted avg       0.79      0.80      0.79       192

